### ISSUE TITLE
CDK version of this stack in Typescript

### ISSUE THREAD

**Issue by Coinhexa** [yannickvr/aws-free-tier-stack#11]
Would be awesome to have a CDK version of this stack in Typescript. I would have said Python but I read that every other language is converted to Typescript from AWS's end
And yes I did read the README where it says cloudformation will be the most friendly

**Comment by yannickvr** [comment]
I'm not absolutely against this, but for what purpose? As it says in the readme, I want to avoid CDK as this stack is targeted towards new users, so "deploy this stack with these 29 error prone steps" kind of misses the point. But I'm interested in other opinions anyway.

Note that if you already have a CDK deployment and just want to include this stack, it's way easier to just include it this way: 

```
cfn_template = cfn_inc.CfnInclude(self, "Template",
    template_file="my-template.yaml"
)
```
